#this attaches a bounding box of the given size to the indicated end effector

string arm_name
string object_name

bool remove

#attach_link aligned values
float64 x_size
float64 y_size
float64 z_size
---
---
