# an action which moves the end_effector to the specified x,y,z position relative to the base_link of the robot

# string name associated with the arm to which the end effector is attached
string arm_name

# which named grasp to use
string grasp_name

# x, y, z point of the grasp
geometry_msgs/Point point

---
motion_planning_msgs/ArmNavigationErrorCodes error_code
---
