<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

  <include filename="$(find rosie_description)/urdf/common/util_defs.xml"/>
  <include filename="$(find rosie_description)/urdf/common/gazebo_sensors.xml"/>  
  <include filename="$(find rosie_description)/urdf/powercube.urdf.xacro"/>
  <include filename="$(find pr2_description)/urdf/common.xacro" />
  <include filename="$(find pr2_description)/urdf/sensors/stereo_camera.urdf.xacro" />

  <!-- Calibration values -->
  <include filename="$(find rosie_description)/calibration/default_cal.xml"/>
  
  <macro name="rosie_camera" params="name parent *origin">
    <joint name="${name}_fixed_joint" type="fixed">
      <insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${name}"/>
    </joint>
    <link name="${name}">
      <inertial>
        <mass value="0.2"/>
        <origin xyz="0 0 0"/>
        <cuboid_inertia_def length="0.10" width="0.10" height="0.10"
                            mass="0.2"/>
      </inertial>
      <visual>
        <origin xyz="0 0 -0.045" rpy="0 0 0"/>
        <geometry>
          <box size="0.05 0.05 0.09"/>
        </geometry>
        <material name="Grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${name}">
      <material value="Gazebo/Red"/>
    </gazebo>
  </macro>

  <macro name="rosie_head" params="parent">

    <joint name="ptu_base_joint" type="fixed">
      <origin xyz="${msr_base_to_ptu_x} ${msr_base_to_ptu_y} ${msr_base_to_ptu_z}"
              rpy="${msr_base_to_ptu_roll} ${msr_base_to_ptu_pitch} ${msr_base_to_ptu_yaw}"/>
      <parent link="${parent}"/>
      <child link="measured_ptu_base"/>
    </joint>

    <link name="measured_ptu_base">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <cuboid_inertia_def length="0.1" width="0.1" height="0.1"
                            mass="0.1"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.001 0.001 0.001"/>
        </geometry>
      </collision>
    </link>
      
    <joint name="head_pan_joint" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 -1"/>
      <limit lower="-1.57" upper="1.57"
             effort="206" velocity="${149 * M_PI/2}"/>
      <safety_controller k_velocity="1.5" soft_lower_limit="-1.565" soft_upper_limit="1.565" k_position="100" />
      <dynamics damping="1.0"/>
      <parent link="measured_ptu_base"/>
      <child link="head_pan_link"/>
    </joint>

    <link name="head_pan_link">
      <inertial>
        <mass value="${arm_elem_pw_mass/2}"/>
        <origin xyz="0 0 ${0.151/2}"/>
        <cuboid_inertia_def length="0.09" width="0.07" height="0.151"
                            mass="${arm_elem_pw_mass/2}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://rosie_description/meshes/other/ptu0.stl"/>
        </geometry>
        <material name="Grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${0.151 / 2}" rpy="0 0 0"/>
        <geometry>
          <box size="0.09 0.07 0.151" />
        </geometry>
      </collision>
    </link>
    
    <gazebo reference="measured_ptu_base">
      <material value="ptu.material"/>
    </gazebo>

    <transmission name="head_pan_trans" type="pr2_mechanism_model/SimpleTransmission">
      <actuator name="head_pan_motor"/>
      <joint name="head_pan_joint"/>
      <mechanicalReduction>1.0</mechanicalReduction>
    </transmission>


    <joint name="head_tilt_joint" type="revolute">
      <origin xyz="0 0 0.101" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.3" upper="1.3"
             effort="35" velocity="${248 * M_PI/2}"/>
      <safety_controller k_velocity="1.5" soft_lower_limit="-1.295" soft_upper_limit="1.295" k_position="100" />
      <dynamics damping="1.0"/>
      <parent link="head_pan_link"/>
      <child link="ptu_tilt_center"/>
    </joint>

    <link name="ptu_tilt_center">
      <inertial>
        <mass value="${arm_elem_pw_mass/2}"/>
        <origin xyz="0 0 ${0.107/2}"/> 
        <cuboid_inertia_def length="0.07" width="0.160" height="0.107"
                            mass="${arm_elem_pw_mass/2}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://rosie_description/meshes/other/ptu1.stl"/>
        </geometry>
        <material name="Grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${0.107}" rpy="0 0 0"/>
        <geometry>
          <box size="0.070 0.160 0.107" />
        </geometry>
      </collision>
    </link>

    <gazebo reference="ptu_tilt_center">
      <material value="ptu.material"/>
    </gazebo>

    <transmission name="head_tilt_trans" type="pr2_mechanism_model/SimpleTransmission">
      <actuator name="head_tilt_motor"/>
      <joint name="head_tilt_joint"/>
      <mechanicalReduction>1.0</mechanicalReduction>
    </transmission>

<!--
    <joint name="ptu_center_to_dummy_fixed_joint" type="fixed">
      <origin xyz="${cal_ptu_cam_x_offset} ${cal_ptu_cam_y_offset} ${cal_ptu_cam_z_offset + 0.07}"
              rpy="0 0 0"/>
      <parent link="ptu_tilt_center"/>
      <child link="ptu_cam_dummy"/>
    </joint>

    <link name="ptu_cam_dummy">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <cuboid_inertia_def length="0.10" width="0.10" height="0.10"
                            mass="0.1"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0"/>
        <geometry>
          <box size="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0"/>
        <geometry>
          <box size="0.001 0.001 0.001"/>
        </geometry>
      </collision>
    </link>

    <joint name="dummy_to_ptu_fixed_joint" type="fixed">
      <origin xyz="0 0 0"
              rpy="${-0.5 * M_PI} 0 ${-0.5 * M_PI}"/>
      <parent link="ptu_cam_dummy"/>
      <child link="ptu"/>
    </joint>

    <link name="ptu">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <cuboid_inertia_def length="0.10" width="0.10" height="0.10"
                            mass="0.1"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0"/>
        <geometry>
          <box size="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0"/>
        <geometry>
          <box size="0.001 0.001 0.001"/>
        </geometry>
      </collision>
    </link>
-->
    <rosie_camera name="RightEyeCalc" parent="ptu_tilt_center">
      <origin xyz="${cal_ptu_to_r_cam_x} ${cal_ptu_to_r_cam_y} ${cal_ptu_to_r_cam_z}" rpy="${cal_ptu_to_r_cam_roll} ${cal_ptu_to_r_cam_pitch} ${cal_ptu_to_r_cam_yaw}"/>
    </rosie_camera>

    <rosie_camera name="LeftEyeCalc" parent="RightEyeCalc">
      <origin xyz="${cal_r_cam_to_l_cam_x} ${cal_r_cam_to_l_cam_y} ${cal_r_cam_to_l_cam_z}"
              rpy="${cal_r_cam_to_l_cam_roll} ${cal_r_cam_to_l_cam_pitch} ${cal_r_cam_to_l_cam_yaw}"/>
    </rosie_camera>

    <rosie_camera name="sr4" parent="RightEyeCalc">
      <origin xyz="${cal_r_cam_to_sr4_x} ${cal_r_cam_to_sr4_y} ${cal_r_cam_to_sr4_z}"
              rpy="${cal_r_cam_to_sr4_roll} ${cal_r_cam_to_sr4_pitch} ${cal_r_cam_to_sr4_yaw}"/>
    </rosie_camera>

    <rosie_camera name="openni_camera" parent="RightEyeCalc">
      <origin xyz="${cal_r_cam_to_kinect_x} ${cal_r_cam_to_kinect_y} ${cal_r_cam_to_kinect_z}"
              rpy="${cal_r_cam_to_kinect_roll} ${cal_r_cam_to_kinect_pitch} ${cal_r_cam_to_kinect_yaw}"/>
    </rosie_camera>

    <camera_sensor name="RightEyeCalc_sensor" link="RightEyeCalc">
      <origin xyz="0 0 0" rpy="0 ${-0.5 * M_PI} ${0.5 * M_PI}"/>
    </camera_sensor>

    <camera_sensor name="LeftEyeCalc_sensor" link="LeftEyeCalc">
      <origin xyz="0 0 0" rpy="0 ${-0.5 * M_PI} ${0.5 * M_PI}"/>
    </camera_sensor>

    <!--Simulated Videre STOC Camera-->
    <stereo_camera_v0 parent="RightEyeCalc" name="wide_stereo" focal_length="320" hfov="90" image_format="BAYER_BGGR8" image_width="640" image_height="480" >
      <origin xyz="${cal_r_cam_to_stoc_x} ${cal_r_cam_to_stoc_y} ${cal_r_cam_to_stoc_z}" 
	      rpy="${cal_r_cam_to_stoc_roll} ${cal_r_cam_to_stoc_pitch} ${cal_r_cam_to_stoc_yaw}" />
    </stereo_camera_v0>

    
    <!-- <swissranger_sr4000 name="sr4_sensor" link="sr4"> -->
    <!--   <origin xyz="0 0 0" rpy="0 ${-0.5 * M_PI} 0"/> -->
    <!-- </swissranger_sr4000> -->
  </macro>
  
</robot>
