all_ver25032010: Makefile
	rm -f all_ver*
	rm -f cop_resource.tar.gz*
	wget http://ias.in.tum.de/~klank/cop_resource.tar.gz
	tar -xzf  cop_resource.tar.gz
	touch all_ver25032010
clean:
	rm -rf resource cop_resource.tar.gz
	rm -f all_ver*
