all_ver26082010: Makefile
	rm -f all_ver*
	rm -f cop_resourc*.tar.gz
	wget http://ias.in.tum.de/~klank/cop_resource_26082010.tar.gz
	tar -xzf  cop_resource_26082010.tar.gz
	chmod -R a+w resource/
	touch all_ver26082010
	
clean:
	rm -rf resource cop_resourc*.tar.gz
	rm -f all_ver*
