#Descriptors of models used in cop, U. Klank klank@in.tum.de
uint64  object_id          # unique id that could be used for a query
string  sem_class          # connected semantic concept
string  type               # Class name that was used to generate the corresponding cop descriptor plugin, 
                           # example are: ShapeModel, ColorClass, DeformShapeModel
float64 quality            # the current quality assinged to this descriptor



