#Message that cop uses to  answer on specified topics, U. Klank klank@in.tum.de
uint64         perception_primitive         # Perception primitive that caused this answer
float64        evaluation                   # A score describing the quality of the outcomes of the perception primitive
system_error[] error                        # A list of occured system failures which might be caused by the perception primitive
