# Cop call,  U. Klank klank@in.tum.de
# Message to query cop
string outputtopic         #name of the topic where the answer should be published
string[] object_classes    #descriptor/object class name
uint64[] object_ids        #id of an previously seen object
uint64 action_type       #actiontype: e.g. track = 0x100 locate: 0x000
uint64 number_of_objects #number of objects
vision_msgs/apriori_position[] list_of_poses 	   #pose matrix, fully projective 4x4 matrix
---