## This file should be loaded under <robot description>_collision

default_collision_operations:
  - object1: robot_body
    object2: right_arm
    operation: enable

  - object1: robot_body
    object2: left_arm
    operation: enable

  - object1: robot_body
    object2: l_end_effector
    operation: enable

  - object1: robot_body
    object2: r_end_effector
    operation: enable

  - object1: left_arm
    object2: right_arm
    operation: enable

  - object1: l_end_effector
    object2: right_arm
    operation: enable

  - object1: l_end_effector
    object2: left_arm
    operation: disable

  - object1: r_end_effector
    object2: left_arm
    operation: enable

  - object1: r_end_effector
    object2: right_arm
    operation: disable

  - object1: l_end_effector
    object2: r_end_effector
    operation: enable

  - object1: calib_right_arm_base_link
    object2: calib_left_arm_base_link
    operation: disable

  - object1: torso_link
    object2: calib_right_arm_base_link
    operation: disable

  - object1: torso_link
    object2: calib_left_arm_base_link
    operation: disable

  - object1: torso_link
    object2: right_arm_1_link
    operation: disable

  - object1: torso_link
    object2: left_arm_1_link
    operation: disable

  - object1: torso_link
    object2: right_arm_2_link
    operation: disable

  - object1: torso_link
    object2: left_arm_2_link
    operation: disable
