## This file should be loaded under <robot description>_planning

## the definition of each group
groups:

  - name: robot_body
    joints:
      base_torso_joint
      head_pan_joint
      head_tilt_joint
    links:
      base_link
      torso_link
      head_pan_link
      ptu_tilt_center

  - name: left_arm
    joints:
      left_arm_0_joint
      left_arm_1_joint
      left_arm_2_joint
      left_arm_3_joint
      left_arm_4_joint
      left_arm_5_joint
      left_arm_6_joint
    links:
      calib_left_arm_base_link
      left_arm_1_link
      left_arm_2_link
      left_arm_3_link
      left_arm_4_link
      left_arm_5_link
      left_arm_6_link
      left_arm_7_link
      left_arm_hand_link

  - name: right_arm
    joints:
      right_arm_0_joint
      right_arm_1_joint
      right_arm_2_joint
      right_arm_3_joint
      right_arm_4_joint
      right_arm_5_joint
      right_arm_6_joint
    links:
      calib_right_arm_base_link
      right_arm_1_link
      right_arm_2_link
      right_arm_3_link
      right_arm_4_link
      right_arm_5_link
      right_arm_6_link
      right_arm_7_link
      right_arm_hand_link

  - name: l_end_effector
    links:
     left_hand_palm
     left_hand_thumb_base

  - name: r_end_effector
    links:
     right_hand_palm
     right_hand_thumb_base
