name = TestMicroEdgeCorrectionTable
type = executable
includeDirectories =
libraries =
libraryDirectories =
classes = AdaptiveRasterizer Image MemoryImage OwnedImage MomentMask EdgeImage MicroEdgeMap MicroEdgeCorrectionTable MicroEdgeDetector

include makefiles/Makefile.build
